import 'package:get_storage/get_storage.dart';
import 'package:mlimi/services/notification_service.dart';

class LanguageService {
  static Map<String, Map<String, String>> translations = {
    'en': {
      'weather': 'Weather',
      'financialLiteracy': 'Financial Literacy',
      'viewMore': 'View more >',
      'loading': 'Loading...',
      'errorLoading': 'Error loading data',
      'noData': 'No data found',
      'tryAgain': 'Try Again',
      'menu': 'Menu',
      'settings': 'Settings',
      'myAccount': 'My Account',
      'changeLanguage': 'Sinthani chiyankhulo KuChichewa',
      'failedWeather': 'Failed to load Weather data. Please try again.',
      'failedFinancial': 'Failed to load Financial Literacy information.',
      // Aggregation Dashboard
      'groupAggregation': 'Group Aggregation',
      'systemOverview': 'System Overview',
      'totalVolume': 'Total Volume',
      'remaining': 'Remaining',
      'totalRevenue': 'Total Revenue',
      'aggregationsLedgers': 'Aggregations Ledgers',
      'startAggregation': 'Start Aggregation',
      'activePools': 'Active Pools',
      'completed': 'Completed',
      'open': 'Open',
      'partialSold': 'Partial Sold',
      // Start Aggregation Screen
      'startPool': 'Start Pool',
      'initializePool': 'Initialize a new pool',
      'definePoolInfo': 'Define which group and commodity this aggregation is for.',
      'selectGroup': 'Select Group',
      'selectCommodity': 'Select Commodity (Value Chain)',
      'measurementUnit': 'Measurement Unit',
      'kilogramsKg': 'Kilograms (Kg)',
      'tonnesT': 'Tonnes (T)',
      'bags': 'Bags',
      'initializeAggregation': 'Initialize Aggregation',
      'required': 'Required',
      'invalid': 'Invalid',
      'successStart': 'Aggregation started successfully!',
      'failedStart': 'Failed to start aggregation',
      // Details Screen
      'contributions': 'Contributions',
      'salesHistory': 'Sales History',
      'earnings': 'Earnings',
      'stock': 'Stock',
      'total': 'Total',
      'price': 'Price',
      'noContributions': 'No contributions yet',
      'noSales': 'No sales recorded',
      'noEarnings': 'No earnings data available',
      'broadcastSent': 'Broadcast sent — awaiting buyers',
      'poolCompleted': 'Pool completed — fully sold',
      'finalizeBroadcast': 'Finalize & Broadcast',
      'add': 'Add',
      'sell': 'Sell',
      'deletePool': 'Delete Pool',
      'deleteConfirm': 'Are you sure? This will delete all contributions and sales data.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      // Bottom Sheets & Forms
      'addContribution': 'Add Contribution',
      'existingMember': 'Existing Member',
      'newMember': 'New Member',
      'selectMember': 'Select Member',
      'fullName': 'Full Name',
      'phoneNumber': 'Phone Number',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'ageRange': 'Age Range',
      'quantityContributed': 'Quantity Contributed (kg)',
      'submitContribution': 'Submit Contribution',
      'recordSale': 'Record Sale',
      'availableStock': 'Available Stock',
      'existingBuyer': 'Existing Buyer',
      'newBuyer': 'New Buyer',
      'selectBuyer': 'Select Buyer',
      'buyerName': 'Buyer Name',
      'buyerPhone': 'Buyer Phone',
      'buyerLocation': 'Buyer Location',
      'quantityKg': 'Quantity (kg)',
      'priceUnit': 'Price/Unit',
      'confirmSale': 'Confirm Sale',
      'dateSold': 'Date of Sale (optional)',
      'updateContribution': 'Update Contribution',
      'edit': 'Edit',
      'member': 'Member',
      'invalidNumber': 'Invalid number',
      'overLimit': 'Over limit',
      'successRecordSale': 'Sale recorded successfully!',
      'successAddContribution': 'Contribution added successfully!',
      'successUpdateContribution': 'Contribution updated successfully!',
      // Broadcast Config Modal
      'broadcastAggregation': 'Broadcast Aggregation',
      'selectRecipientDesc': 'Select who should receive this alert',
      'matchedMarketActors': 'Matched Market Actors',
      'noMatchedActors': 'No matched market actors for this value chain.',
      'businessProfiles': 'Business Profiles',
      'noMatchedBusinesses': 'No matched businesses for this value chain.',
      'extraContacts': 'Extra Contacts',
      'addExtraPhone': 'Add extra phone number...',
      'addExtraEmail': 'Add extra email address...',
      'finalizeSendAlerts': 'Finalize & Send Alerts',
      'successBroadcast': 'Broadcast completed successfully!',
      'failedBroadcast': 'Failed to broadcast',
      // Insights
      'insights': 'Insights',
      'volumeAnalytics': 'Volume Analytics',
      'aggregated': 'Aggregated',
      'sold': 'Sold',
      'remain': 'Remain',
      // Notification strings
      'notifPermTitle': 'Allow Mlimi App Notifications',
      'notifPermMsg': 'Enable notifications to get market prices, farming tips and important updates.',
      'notifCommodityPosted': 'New Commodity Listed!',
      'notifTrendingPublished': 'New Story on Mlimi App!',
      'notifWelcome': 'Welcome to Mlimi App!',
      'notifMarketActor': 'New Market Actor Added!',
      'notifBusinessProfile': 'New Business Profile Created!',
      'notifLowStock': 'Low Stock Warning!',
      'notifDailyTip': 'Today\'s Farming Tip',
    },
    'ny': {
      'weather': 'Nyengo',
      'financialLiteracy': 'Ndalama ndi Bizinesi',
      'viewMore': 'Onani zambiri >',
      'loading': 'Kudikira...',
      'errorLoading': 'Palakwika potsitsa data',
      'noData': 'Palibe data yapezeka',
      'tryAgain': 'Yesaninso',
      'menu': 'Menyu',
      'settings': 'Makonda',
      'myAccount': 'Akaunti Yanga',
      'changeLanguage': 'Change to English',
      'failedWeather': 'Palakwika potsitsa data ya nyengo. Chonde yesesni.',
      'failedFinancial': 'Palakwika potsitsa data ya ndalama.',
      // Aggregation Dashboard
      'groupAggregation': 'Zosonkhanitsa pa Gulu',
      'systemOverview': 'Zambiri za Ndondomeko',
      'totalVolume': 'Mulingo Onse',
      'remaining': 'Zotsalira',
      'totalRevenue': 'Phindu Lanu',
      'aggregationsLedgers': 'Mabuku Azosonkhanitsa',
      'startAggregation': 'Yambitsani Zosonkhanitsira',
      'activePools': 'Malo Ogwira Ntchito',
      'completed': 'Kutsirizidwa',
      'open': 'Zotsegula',
      'partialSold': 'Zogulitsidwako',
      // Start Aggregation Screen
      'startPool': 'Yambitsani Zosonkhanitsa',
      'initializePool': 'Tsegulani Zosonkhanitsira zatsopano',
      'definePoolInfo': 'Fotokozani gulu ndi mbewu yomwe zosonkhanitsira.',
      'selectGroup': 'Sankhani Gulu',
      'selectCommodity': 'Sankhani Mbewu (Value Chain)',
      'measurementUnit': 'muyeso oyezela',
      'kilogramsKg': 'Makilogalamu (Kg)',
      'tonnesT': 'Matani (T)',
      'bags': 'Matumba',
      'initializeAggregation': 'Yambitsani Zosonkhanitsira',
      'required': 'Chofunika',
      'invalid': 'Zolakwika',
      'successStart': 'Zosonkhanitsira zayambitsidwa bwino!',
      'failedStart': 'Zakanika kuyambitsa zosonkhanitsira',
      // Details Screen
      'contributions': 'Zopereka',
      'salesHistory': 'Mbiri ya Zogulitsa',
      'earnings': 'Zopezeka',
      'stock': 'Katundu',
      'total': 'zonse',
      'price': 'Mtengo',
      'noContributions': 'Palibe zopereka zomwe zalembedwa',
      'noSales': 'Palibe zogulitsa zomwe zalembedwa',
      'noEarnings': 'Palibe zopezeka zomwe zilipo',
      'broadcastSent': 'Uthenga watumizidwa — kudikira ogula',
      'poolCompleted': 'zosonkhanitsira zatha — zogulitsidwa zonse',
      'finalizeBroadcast': 'Malizitsani & Tumizani Uthenga',
      'add': 'Onjezerani',
      'sell': 'Gulitsani',
      'deletePool': 'Chotsani Zosonkhanitsira',
      'deleteConfirm': 'Kodi mukutsimikiza? Izi zichotsa zopereka zonse ndi mbiri ya zogulitsa.',
      'cancel': 'Kuletsa',
      'delete': 'kufufuta',
      // Bottom Sheets & Forms
      'addContribution': 'Onjezerani zopereka',
      'existingMember': 'Mmembala wolembedwa kale',
      'newMember': 'Mmembala watsopano',
      'selectMember': 'Sankhani Mmembala',
      'fullName': 'Dzina Lonse',
      'phoneNumber': 'Nambala ya Foni',
      'gender': 'Chikhalidwe (Mwamuna/Mkazi)',
      'male': 'Mwamuna',
      'female': 'Mkazi',
      'ageRange': 'Zaka zanu',
      'quantityContributed': 'Kuchuluka Kosonkhanitsidwa (kg)',
      'submitContribution': 'Perekani Chopereka',
      'recordSale': 'Lembani Zogulitsa',
      'availableStock': 'Zotsalira zomwe zilipo',
      'existingBuyer': 'Wogula wakale',
      'newBuyer': 'Wogula Watsopano',
      'selectBuyer': 'Sankhani Wogula',
      'buyerName': 'Dzina la Wogula',
      'buyerPhone': 'Nambala ya Wogula',
      'buyerLocation': 'Komwe Kuli Wogula',
      'quantityKg': 'Kuchuluka (kg)',
      'priceUnit': 'Mtengo pa Kilo imodzi',
      'confirmSale': 'Tsimikizani Kugulitsa',
      'dateSold': 'Tsiku Logulitsira (osafunikira)',
      'updateContribution': 'Sinthani Chopereka',
      'edit': 'Sinthani',
      'member': 'Mmembala',
      'invalidNumber': 'Nambala yolakwika',
      'overLimit': 'Kupitilira malire',
      'successRecordSale': 'Zogulitsa zalembedwa!',
      'successAddContribution': 'Chopereka chawonjezedwa !',
      'successUpdateContribution': 'Chopereka chasinthidwa !',
      // Broadcast Config Modal
      'broadcastAggregation': 'Falitsani Zosonkhanitsira',
      'selectRecipientDesc': 'Sankhani omwe akuyenera kulandira uthengawu',
      'matchedMarketActors': 'Ogula Mbewu Omwe Alipo',
      'noMatchedActors': 'Palibe ogula mbewu omwe apezeka amtunduwu.',
      'businessProfiles': 'Mabizinesi Athu',
      'noMatchedBusinesses': 'Palibe mabizinesi omwe apezeka amtunduwu.',
      'extraContacts': 'Manambala Ena',
      'addExtraPhone': 'Onjezerani nambala ya foni...',
      'addExtraEmail': 'Onjezerani imelo...',
      'finalizeSendAlerts': 'Malizitsani & Tumizani Machenjezo',
      'successBroadcast': 'Uthenga wafalitsidwa bwino!',
      'failedBroadcast': 'Zakanika kufalitsa uthenga',
      // Insights
      'insights': 'Kafukufuku wathu',
      'volumeAnalytics': 'Kuwunika kwa Kuchuluka',
      'aggregated': 'Zosonkhanitsidwa',
      'sold': 'Zogulitsidwa',
      'remain': 'Zotsalira',
      // Zomuwuza (Notification strings)
      'notifPermTitle': 'Mulole Mlimi App Kutumiza Zomuwuza!',
      'notifPermMsg': 'Chonde mulole ma notification kuti mulandire zankhani za msika, mbewu, ndi zina zambiri.',
      'notifCommodityPosted': 'Katundu Watsopano pa Msika!',
      'notifTrendingPublished': 'Nkhani Yatsopano pa Mlimi App!',
      'notifWelcome': 'Takulandirani pa Mlimi App!',
      'notifMarketActor': 'Wogula Watsopano wa Mbewu Alipo!',
      'notifBusinessProfile': 'Bizinesi Yatsopano Yalembedwa!',
      'notifLowStock': 'Chidwi! Katundu Akutha!',
      'notifDailyTip': 'Uphungu wa Lero pa Ulimi',
    }
  };

  static String getText(String key, String language) {
    return translations[language]?[key] ?? translations['en']?[key] ?? key;
  }

  /// Sync the current language preference to the backend so that push
  /// notifications are delivered in Chichewa (ny) or English (en).
  static Future<void> syncToBackend(String language) async {
    final token = GetStorage().read('token');
    if (token == null) return;
    await NotificationService().syncLanguageToBackend(language);
  }
}
